[package]
name = "hello-world"
version = "1.0.0"
authors = "https://github.com/kazandiran/Actix-web"
edition = "2021"

[dependencies]
actix-web.workspace = true
env_logger.workspace = true
log.workspace = true
